template: Hello Welcome to TruFeed

storage:
  rootDir: /Users/sinhar/Personal/db
  userStore:
    name: user
    path: /user
    maxFileSize: 
  feedStore:
    name: feed
    path: /feed
    maxFileSize: 64